[package]
name = "k"
version = "0.1.0"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]
description = "k is for kinematics"
license = "Apache-2.0"
keywords = ["kinematics", "robotics", "ik"]
categories = ["algorithms"]
repository = "https://github.com/OTL/k"
documentation = "http://docs.rs/k"
readme = "README.md"

[dependencies]
nalgebra = "0.13.0"
urdf-rs = "0.2.0"
log = "0.3"

[dev-dependencies]
kiss3d = "0.11.0"
glfw = { version = "0.15.0", default-features = false }
