[package]
name = "k"
version = "0.20.0"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]
description = "k is for kinematics"
license = "Apache-2.0"
keywords = ["kinematics", "robotics", "ik"]
categories = ["algorithms"]
repository = "https://github.com/OTL/k"
documentation = "http://docs.rs/k"
readme = "README.md"
edition = "2018"
build = "build.rs"

[dependencies]
nalgebra = "0.21"
urdf-rs = "0.4"
log = "0.4"
simba = "0.1"
thiserror = "1.0"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"
kiss3d = "0.24"
rand = "0.7"

#[profile.release]
#debug = true

#[profile.bench]
#debug = true
